# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
 

  desc "Build the app"
  lane :build do
    build_app(
  scheme: "YourAppScheme",
  export_method: "development",
  export_options: {
    compileBitcode: false,
    manageAppVersionAndBuildNumber: false,
    signingStyle: "automatic",
    signingCertificate: "Apple Development",
    provisioningProfiles: {
      "com.your.bundle.id" => "match Development com.your.bundle.id"
    }
  }
)
  end
end
